-- JOBLANTIS seed – kompetencia swipe kártyák munkakörönként (15–20 db)
-- Jobbra: igen, ez megy · Balra: nem · Fel: ebben kifejezetten erős vagyok

with data (template_slug, competency_slug, statement) as (values
  -- Szakács
  ('szakacs', 'haccp', 'Ismerem a HACCP-szabályokat, és a napi dokumentációt is vezettem'),
  ('szakacs', 'haccp', 'Tudom, milyen hőmérsékleten kell tárolni a nyers húst és a kész ételt'),
  ('szakacs', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('szakacs', 'keskezeles', 'Gyorsan és egyenletesen vágok julienne-t és brunoise-t'),
  ('szakacs', 'keskezeles', 'Magam élezem és ápolom a késeimet'),
  ('szakacs', 'adagolas-recept', 'Pontosan követem a receptúrát, grammra adagolok'),
  ('szakacs', 'adagolas-recept', 'Tudok receptet felszorozni 10 főről 100 főre'),
  ('szakacs', 'meleg-konyha', 'Önállóan viszek egy meleg konyhai szekciót (pl. grill vagy sauté)'),
  ('szakacs', 'meleg-konyha', 'Alaplevet és mártást alapból készítek'),
  ('szakacs', 'hideg-konyha', 'Hideg előételeket és salátákat készre teszek szerviz előtt'),
  ('szakacs', 'hideg-konyha', 'Szerviz előtt egyedül összeállítom a teljes mise en place-t'),
  ('szakacs', 'a-la-carte-konyha', 'Dolgoztam à la carte étteremben, rendelésre főzve'),
  ('szakacs', 'bankett-konyha', 'Főztem már 200+ fős bankettre'),
  ('szakacs', 'allergen', 'Ismerem a 14 kötelezően jelölendő allergént'),
  ('szakacs', 'allergen', 'Allergiás vendég ételét külön eszközökkel, keresztszennyeződés nélkül készítem'),
  ('szakacs', 'csucsidos-terhelhetoseg', 'Csúcsidőben 30+ nyitott rendelés mellett is tartom a tempót'),
  ('szakacs', 'csucsidos-terhelhetoseg', 'Dupla műszakot is végig tudok dolgozni minőségromlás nélkül'),

  -- Séf / konyhafőnök
  ('sef', 'menutervezes', 'Állítottam össze teljes, szezonális étlapot'),
  ('sef', 'menutervezes', 'Ki tudom számolni egy fogás anyagköltségét és food cost arányát'),
  ('sef', 'menutervezes', 'Készítettem receptúra-adatlapot (normát) az ételekhez'),
  ('sef', 'konyhai-csapatvezetes', 'Vezettem 5+ fős konyhai csapatot'),
  ('sef', 'konyhai-csapatvezetes', 'Készítettem heti beosztást a konyhai személyzetnek'),
  ('sef', 'konyhai-csapatvezetes', 'Betanítottam új szakácsokat'),
  ('sef', 'beszerzes', 'Tárgyaltam beszállítókkal árról és minőségről'),
  ('sef', 'beszerzes', 'Napi rendelést adtam le a készlet és a foglalások alapján'),
  ('sef', 'arukeszlet-fifo', 'Havi leltárt vezettem, és kezeltem a selejtet'),
  ('sef', 'arukeszlet-fifo', 'Következetesen alkalmazom és betartatom a FIFO elvet'),
  ('sef', 'haccp', 'Felelős voltam egy konyha HACCP-rendszeréért'),
  ('sef', 'haccp', 'Végigvittem hatósági (NÉBIH) ellenőrzést'),
  ('sef', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('sef', 'allergen', 'Allergénmátrixot készítettem az étlaphoz'),
  ('sef', 'a-la-carte-konyha', 'Vezettem a passzt à la carte szerviz alatt'),
  ('sef', 'tanyeralas', 'Kialakítottam az ételek tálalási standardját fotóval'),
  ('sef', 'nyelv-angol', 'Angolul is tudok konyhai utasítást adni'),

  -- Konyhai kisegítő
  ('konyhai-kisegito', 'haccp', 'Ismerem a HACCP alapszabályait (kézmosás, színkódos vágódeszkák)'),
  ('konyhai-kisegito', 'haccp', 'Tudom, hogyan kell címkézni és dátumozni az előkészített alapanyagot'),
  ('konyhai-kisegito', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('konyhai-kisegito', 'elokeszites', 'Gyorsan pucolok és darabolok nagy mennyiségű zöldséget'),
  ('konyhai-kisegito', 'elokeszites', 'Tudok húst előkészíteni (inazás, porciózás)'),
  ('konyhai-kisegito', 'elokeszites', 'Szerviz előtt önállóan előkészítem, amit a szakács kér'),
  ('konyhai-kisegito', 'keskezeles', 'Biztonságosan bánok a késsel, ismerem az alapvágásokat'),
  ('konyhai-kisegito', 'keskezeles', 'Tudok halat filézni'),
  ('konyhai-kisegito', 'arukeszlet-fifo', 'Áruátvételnél ellenőrzöm a hőmérsékletet és a lejáratot'),
  ('konyhai-kisegito', 'arukeszlet-fifo', 'A hűtőket FIFO szerint rendben tartom'),
  ('konyhai-kisegito', 'konyhai-gepek', 'Kezeltem szeletelőgépet és robotgépet'),
  ('konyhai-kisegito', 'konyhai-gepek', 'Alapprogramokkal tudok kombi párolót kezelni'),
  ('konyhai-kisegito', 'tisztitoszerek', 'Tudom, melyik tisztítószert hogyan kell hígítani'),
  ('konyhai-kisegito', 'csucsidos-terhelhetoseg', 'Csúcsidőben is több feladatot viszek párhuzamosan'),
  ('konyhai-kisegito', 'csucsidos-terhelhetoseg', 'Bírom a 8–10 órás állómunkát'),

  -- Mosogató
  ('mosogato', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('mosogato', 'mosogatogep', 'Kezeltem ipari (szalagos vagy alagút) mosogatógépet'),
  ('mosogato', 'mosogatogep', 'Ellenőrzöm a mosogatógép mosó- és öblítővizének hőmérsékletét'),
  ('mosogato', 'mosogatogep', 'Be tudom állítani a vegyszeradagolót'),
  ('mosogato', 'mosogatogep', 'Szűrőtisztítást, apróbb dugulást magam megoldok'),
  ('mosogato', 'tisztitoszerek', 'Ismerem a használt vegyszerek biztonsági adatlapját'),
  ('mosogato', 'tisztitoszerek', 'Védőfelszerelést (kesztyű, szemüveg) következetesen használok'),
  ('mosogato', 'tisztitoszerek', 'Tudom, hogy a klóros és a savas szert tilos összekeverni'),
  ('mosogato', 'takaritasi-terv', 'Takarítási terv szerint dolgozom, és dokumentálom'),
  ('mosogato', 'takaritasi-terv', 'Zsíros gasztro edényt gyorsan tisztára mosok'),
  ('mosogato', 'takaritasi-terv', 'Zárás után önállóan kitakarítom a konyhát'),
  ('mosogato', 'haccp', 'Tudom, mi a különbség a tisztítás és a fertőtlenítés között'),
  ('mosogato', 'haccp', 'Ismerem a hulladék és a moslék szabályos kezelését'),
  ('mosogato', 'csucsidos-terhelhetoseg', 'Bankett után is lépést tartok a visszaérkező edényekkel'),
  ('mosogato', 'csucsidos-terhelhetoseg', 'Bírom a tempót egy 300 terítékes szerviz alatt'),

  -- Pincér
  ('pincer', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('pincer', 'a-la-carte-felszolgalas', 'Dolgoztam à la carte étteremben felszolgálóként'),
  ('pincer', 'a-la-carte-felszolgalas', 'Ismerem a fogások sorrendjét és tempóját'),
  ('pincer', 'a-la-carte-felszolgalas', 'Fejből tudom az étlapot az összetevőkkel együtt'),
  ('pincer', 'teritesi-szabalyok', 'Tudok formális, többfogásos terítést készíteni'),
  ('pincer', 'teritesi-szabalyok', 'Ismerem a felszolgálás szabályait (honnan tálalok, honnan szedek)'),
  ('pincer', 'tobb-asztal', 'Csúcsidőben egyedül vittem 8+ asztalt'),
  ('pincer', 'tobb-asztal', 'Egyszerre 3 tányért biztonságosan hordok'),
  ('pincer', 'bankett-felszolgalas', 'Dolgoztam bankettes rendezvényen'),
  ('pincer', 'bankett-felszolgalas', 'Szolgáltam fel 100+ fős esküvőn'),
  ('pincer', 'borismeret', 'Tudok bort ajánlani az ételhez'),
  ('pincer', 'borismeret', 'Szakszerűen nyitok és töltök bort, pezsgőt'),
  ('pincer', 'pos-kassza', 'Használtam éttermi POS rendszert (rendelés, számla, számlabontás)'),
  ('pincer', 'pos-kassza', 'A műszak végén pontosan elszámolok'),
  ('pincer', 'rendelesfelvetel', 'Rendelésfelvételkor ajánlok, és sikeresen növelem a fogyasztást'),
  ('pincer', 'nyelv-angol', 'Angolul is felveszem a rendelést és válaszolok a kérdésekre'),
  ('pincer', 'allergen', 'Ismerem az ételek allergéntartalmát, és tájékoztatom a vendéget'),

  -- Pultos / bartender
  ('pultos', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('pultos', 'koktelkeszites', 'Fejből tudok legalább 20 klasszikus koktélt'),
  ('pultos', 'koktelkeszites', 'Készítettem saját koktélt itallapra'),
  ('pultos', 'koktelkeszites', 'Csúcsidőben óránként 60+ koktélt adok ki'),
  ('pultos', 'italismeret', 'Ismerem a fő párlatkategóriákat (whisky, rum, gin, tequila)'),
  ('pultos', 'italismeret', 'Tudok italt ajánlani a vendég ízlése alapján'),
  ('pultos', 'csapolas', 'Szakszerűen csapolok sört, megfelelő habbal'),
  ('pultos', 'csapolas', 'Tudok hordót cserélni és csapolót tisztítani'),
  ('pultos', 'pos-kassza', 'Kezeltem pultos kasszát készpénzzel és kártyával'),
  ('pultos', 'pos-kassza', 'A napi zárást pontosan elkészítem'),
  ('pultos', 'pult-nyitas-zaras', 'Önállóan nyitom és zárom a pultot'),
  ('pultos', 'pult-nyitas-zaras', 'Vezettem italleltárt'),
  ('pultos', 'felelos-italkiszolgalas', 'Kiskorút nem szolgálok ki, rákérdezek az igazolványra'),
  ('pultos', 'felelos-italkiszolgalas', 'Ittas vendéggel udvariasan, de határozottan bánok'),
  ('pultos', 'csucsidos-terhelhetoseg', 'Telt házas estén is egyedül viszem a pultot'),
  ('pultos', 'nyelv-angol', 'Angolul is gördülékenyen kiszolgálok'),

  -- Barista
  ('barista', 'eu-alkalmassagi', 'Van érvényes egészségügyi alkalmassági igazolásom'),
  ('barista', 'kavegep', 'Be tudom állítani a darálót az extrakciós idő alapján'),
  ('barista', 'kavegep', 'Tudom, mitől lesz savanyú vagy keserű egy eszpresszó'),
  ('barista', 'kavegep', 'Csúcsidőben két karral párhuzamosan dolgozom'),
  ('barista', 'kavegep', 'Óránként 80+ kávét kiadok'),
  ('barista', 'latte-art', 'Tudok latte artot készíteni (szív, tulipán)'),
  ('barista', 'latte-art', 'Bonyolultabb mintát (rozetta, hattyú) is öntök'),
  ('barista', 'latte-art', 'Növényi tejet is selymesre habosítok'),
  ('barista', 'latte-art', 'Csúcsidőben is egyenletes minőségű tejhabot készítek'),
  ('barista', 'kavegep-tisztitas', 'Napi visszamosást és darálótisztítást végzek'),
  ('barista', 'kavegep-tisztitas', 'Figyelem a vízkőmentesítést és a tömítések állapotát'),
  ('barista', 'alternativ-kave', 'Készítek filterkávét V60-nal vagy Chemexszel'),
  ('barista', 'alternativ-kave', 'Ismerem a kávé származását és feldolgozási módjait'),
  ('barista', 'pos-kassza', 'Kezeltem kasszát kávézóban'),
  ('barista', 'haccp', 'Ismerem a tejtermékek tárolási és higiéniai szabályait'),
  ('barista', 'nyelv-angol', 'Angolul is kiszolgálok és ajánlok'),

  -- Recepciós
  ('recepcios', 'pms', 'Dolgoztam szállodai PMS-rendszerben (pl. Opera, Protel)'),
  ('recepcios', 'pms', 'Rögzítek és módosítok foglalást a PMS-ben'),
  ('recepcios', 'pms', 'Készítettem éjszakai zárást (night audit)'),
  ('recepcios', 'pms', 'Kezeltem kulcskártya-rendszert'),
  ('recepcios', 'check-in-out', 'Önállóan végzek check-int és check-outot'),
  ('recepcios', 'check-in-out', 'Csoportos érkezést is gördülékenyen bejelentkeztetek'),
  ('recepcios', 'nyelv-angol', 'Angolul magabiztosan kommunikálok a vendégekkel'),
  ('recepcios', 'nyelv-angol', 'Írásban is válaszolok angol nyelvű vendégmegkeresésre'),
  ('recepcios', 'nyelv-nemet', 'Németül is tudok vendéget fogadni'),
  ('recepcios', 'foglalaskezeles', 'Kezeltem channel managert (pl. Booking, Expedia elérhetőség)'),
  ('recepcios', 'foglalaskezeles', 'Kezeltem már túlfoglalást'),
  ('recepcios', 'penzkezeles-szamlazas', 'Kezelek valutát, kártyás és SZÉP-kártyás fizetést'),
  ('recepcios', 'penzkezeles-szamlazas', 'Kiállítok számlát és díjbekérőt'),
  ('recepcios', 'telefonos-kommunikacio', 'Telefonon udvariasan és gyorsan intézem a vendégkéréseket'),
  ('recepcios', 'vendegregisztracio', 'Ismerem a vendégregisztrációs kötelezettséget (VIZA)'),
  ('recepcios', 'vendegpanasz', 'Elégedetlen vendég panaszát higgadtan kezelem'),
  ('recepcios', 'vendegpanasz', 'Adtam már megoldási javaslatot (upgrade, kompenzáció)'),

  -- Szobaasszony
  ('szobaasszony', 'szobatakaritas', 'Szállodai standard szerint takarítok szobát'),
  ('szobaasszony', 'szobatakaritas', 'A fürdőszobát ellenőrzőlista szerint takarítom'),
  ('szobaasszony', 'szobatakaritas', 'Takarítottam távozó és maradó szobát is'),
  ('szobaasszony', 'agyazas', 'Gyorsan és szabályosan ágyazok'),
  ('szobaasszony', 'agyazas', 'Párnát, törölközőt, bekészítést standard szerint helyezek el'),
  ('szobaasszony', 'normaido', 'Egy műszakban 14+ szobát elvégzek normaidőben'),
  ('szobaasszony', 'normaido', 'Teltházas napon is tartom a tempót'),
  ('szobaasszony', 'tisztitoszerek', 'Tudom, melyik felületre melyik szert kell használni'),
  ('szobaasszony', 'tisztitoszerek', 'A takarítókocsit önállóan feltöltöm és rendben tartom'),
  ('szobaasszony', 'minibar', 'Minibárt töltök fel, és leltárt vezetek'),
  ('szobaasszony', 'minibar', 'Jelentem a minibár-fogyasztást a recepciónak'),
  ('szobaasszony', 'hibabejelentes', 'A hibákat azonnal jelentem a karbantartásnak'),
  ('szobaasszony', 'hibabejelentes', 'A talált tárgyat szabály szerint kezelem'),
  ('szobaasszony', 'textilkezeles', 'A szennyes és a tiszta textilt elkülönítve kezelem'),
  ('szobaasszony', 'textilkezeles', 'A foltos, sérült textilt felismerem és kiszortírozom'),

  -- Hostess
  ('hostess', 'vendegfogadas', 'Mosolyogva és határozottan fogadom a vendégeket'),
  ('hostess', 'vendegfogadas', 'Ültetésnél figyelek a felszolgálók egyenletes terhelésére'),
  ('hostess', 'vendegfogadas', 'A visszatérő és VIP vendégeket név szerint fogadom'),
  ('hostess', 'asztalfoglalas', 'Kezeltem online asztalfoglaló rendszert'),
  ('hostess', 'asztalfoglalas', 'A telefonos foglalást pontosan rögzítem'),
  ('hostess', 'asztalfoglalas', 'Készítettem ültetési tervet egy estére'),
  ('hostess', 'varolista', 'Telt háznál várólistát kezelek, és reális várakozási időt mondok'),
  ('hostess', 'varolista', 'Koordinálom az asztalforgást a felszolgálókkal'),
  ('hostess', 'telefonos-kommunikacio', 'Telefonon udvariasan kezelem a foglalást és a módosítást'),
  ('hostess', 'telefonos-kommunikacio', 'E-mailben is válaszolok foglalási kérdésekre'),
  ('hostess', 'nyelv-angol', 'Angolul fogadom és útbaigazítom a vendégeket'),
  ('hostess', 'nyelv-angol', 'Angolul is kezelek telefonos foglalást'),
  ('hostess', 'nyelv-nemet', 'Németül is fogadok vendéget'),
  ('hostess', 'vendegpanasz', 'A várakozás miatt türelmetlen vendéget megnyugtatom'),
  ('hostess', 'vendegpanasz', 'A panaszt továbbítom, és utánakövetem')
),
numbered as (
  select d.*, row_number() over (partition by d.template_slug) as sort_order from data d
)
insert into public.swipe_cards (template_id, kind, statement, competency_id, polarity, sort_order)
select t.id, 'competency', n.statement, c.id, 1, n.sort_order
from numbered n
join public.job_role_templates t on t.slug = n.template_slug
join public.competencies c on c.slug = n.competency_slug
on conflict (coalesce(template_id, 0), statement) do update set
  competency_id = excluded.competency_id, sort_order = excluded.sort_order;
