"""A supabase/migrations és supabase/seed fájlokból két, a Supabase SQL Editorba bemásolható fájlt készít:
supabase/sql-editor/1_schema.sql és 2_seed.sql.  Futtatás: python3 scripts/build-sql-editor.py"""
import glob
import os

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "supabase")


def strip_comments(sql):
    """Teljes soros -- megjegyzések és üres sorok elhagyása: a böngészős SQL Editor bemásoláskor félreértheti őket."""
    return "\n".join(l for l in sql.splitlines() if l.strip() and not l.lstrip().startswith("--"))


def build(name, header, files, footer=(), prelude=None):
    out = list(header) + ["", "begin;", ""]
    if prelude:
        out += [strip_comments(open(prelude).read()), ""]
    for f in files:
        out += [strip_comments(open(f).read()), ""]
    out += list(footer) + ["commit;", ""]
    os.makedirs(os.path.join(root, "sql-editor"), exist_ok=True)
    open(os.path.join(root, "sql-editor", name), "w").write("\n".join(out))


migs = sorted(glob.glob(os.path.join(root, "migrations", "*.sql")))
build(
    "1_schema.sql",
    ["-- JOBLANTIS 1/2 schema (re-runnable, deletes existing JOBLANTIS data). Generated by scripts/build-sql-editor.py"],
    migs,
    [
        "create schema if not exists joblantis_internal;",
        "create table if not exists joblantis_internal.migrations (name text primary key, applied_at timestamptz not null default now());",
        "insert into joblantis_internal.migrations (name) values\n  "
        + ",\n  ".join(f"('{os.path.basename(m)}')" for m in migs)
        + "\non conflict do nothing;",
        "",
    ],
    prelude=os.path.join(root, "sql-editor", "0_reset.sql.part"),
)
build(
    "2_seed.sql",
    ["-- JOBLANTIS 2/2 seed data, run after 1_schema.sql. Generated by scripts/build-sql-editor.py"],
    sorted(glob.glob(os.path.join(root, "seed", "*.sql"))),
)
print("supabase/sql-editor/1_schema.sql, 2_seed.sql kész")
